name: Deploy Reveal.js to Mittwald

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js (für Reveal.js)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: (Optional) Build Reveal.js
      run: npm run build

    - name: Deploy via SSH to Mittwald
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.MITTWALD_HOST }}
        username: ${{ secrets.MITTWALD_USER }}
        key: ${{ secrets.MITTWALD_SSH_KEY }}
        port: 22
        source: "dist/*"
        target: "/html/linux-presentation-x84vt"

