name: Deploy reveal.js to Mittwald

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MITTWALD_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Wichtig: SSH-Host-Key automatisch akzeptieren
        ssh-keyscan -H ${{ secrets.MITTWALD_HOST }} >> ~/.ssh/known_hosts
    
    - name: Test SSH Connection
      run: |
        ssh -v ${{ secrets.MITTWALD_USER }}@${{ secrets.MITTWALD_HOST }} "echo 'SSH connection successful'"
    
    - name: Deploy via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.git' \
          --exclude '.github' \
          --exclude 'node_modules' \
          --exclude '.gitignore' \
          ./ ${{ secrets.MITTWALD_USER }}@${{ secrets.MITTWALD_HOST }}:${{ secrets.MITTWALD_PATH }}
