name: Deploy to Mittwald

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    
    - name: Deploy files
      env:
        SSHPASS: ${{ secrets.MITTWALD_PASSWORD }}
      run: |
        # Code zum Server kopieren
        sshpass -e rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.git' \
          --exclude '.github' \
          --exclude 'node_modules' \
          --exclude '.gitignore' \
          ./ ${{ secrets.MITTWALD_USER }}@${{ secrets.MITTWALD_HOST }}:${{ secrets.MITTWALD_PATH }}/
    
    - name: Install dependencies and restart
      env:
        SSHPASS: ${{ secrets.MITTWALD_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no \
          ${{ secrets.MITTWALD_USER }}@${{ secrets.MITTWALD_HOST }} \
          "cd ${{ secrets.MITTWALD_PATH }} && npm install && mittnitectl job restart node"
