name: Test Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Debug SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MITTWALD_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Fingerprint anzeigen
        ssh-keygen -l -f ~/.ssh/deploy_key
        
        # Verbose connection test
        ssh -vvv -i ~/.ssh/deploy_key \
          -o StrictHostKeyChecking=no \
          ${{ secrets.MITTWALD_USER }}@${{ secrets.MITTWALD_HOST }} \
          "pwd && ls -la"
