name: Deploy to Mittwald

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup SSH
      run: |
        # SSH-Verzeichnis erstellen
        mkdir -p ~/.ssh
        
        # Private Key speichern
        echo "${{ secrets.MITTWALD_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Host Key speichern (verhindert Prompt)
        ssh-keyscan -H ${{ secrets.MITTWALD_HOST }} >> ~/.ssh/known_hosts
        
        # SSH-Config für bessere Kompatibilität
        echo "Host mittwald" >> ~/.ssh/config
        echo "  HostName ${{ secrets.MITTWALD_HOST }}" >> ~/.ssh/config
        echo "  User ${{ secrets.MITTWALD_USER }}" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
    
    - name: Test Connection
      run: ssh mittwald "echo 'Connection successful'"
    
    - name: Deploy
      run: |
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          ./ mittwald:${{ secrets.MITTWALD_PATH }}
